### ISSUE TITLE
Move All secrets from repository settings to Azure environment settings  

### ISSUE THREAD

**Issue by Magik3a** [s2kdesign-com/CoinGardenWorld#9]
### 1. Move the secrets from here https://github.com/s2kdesign-com/CoinGardenWorld/settings/secrets/actions

![image](https://user-images.githubusercontent.com/10474555/227159228-55fce479-ddb7-48db-984d-dd44c99bc7a7.png)

### 2.  To azure environment here https://github.com/s2kdesign-com/CoinGardenWorld/settings/environments/932587639/edit
![image](https://user-images.githubusercontent.com/10474555/227159547-2d1aa115-b04c-4b3d-b6e2-49fb590249c4.png)

### 3. And change all actions currently deploying to azure 

```
jobs:
  deploy-to-azure
    environment:
      name: azure 
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
```
